### ISSUE TITLE
It doesn't work in my repo

### ISSUE THREAD

**Issue by eduf** [vrypan/jekyll-post-via-web#1]
That's the message that I got:

"404: Not Found
If you are using two-factor-auth, you will ahve to create a personal access token with "repo" permissions and use this instead of your password."

The URL that I got:
https://eduf.github.io/cms.html?title=Teste+de+Jekyll+CMS&body=Ser%C3%A1+que+funciona%3F

I've created the token, but I don't have how to use it in the CMS form.

**Comment by vrypan** [comment]
Xmm.. It looks like "github_username" is not set in _config.yml

Set `github_username: eduf` in _config.yml

**Comment by eduf** [comment]
Thank you.

File updated.
But, unfortunately, the CMS still doesn’t work.

I get the same message, but not the URL anymore.
Now it is just https://eduf.github.io/cms.html

Best.

On Sat, May 30, 2015 at 9:14 AM, Panayotis Vryonis <notifications@github.com

**Comment by vrypan** [comment]
@eduf, I noticed that your repo is named edu.github.com, the script expects it to be edu.github.io.

If this is the problem, a quick fix would be changing line 110 to:

`var API_NEW_POST = 'https://api.github.com/repos/{{ site.github_username }}/{{ site.github_username }}.github.com/contents/_posts/' ;
`

(ie replace "github.io" with "github.com")

**Comment by eduf** [comment]
It’s working now.
Thanks.

Maybe older repos like mine would need that fix too.
